In [7]:
print("Problem 5")

Problem 5


In [6]:
import numpy as np  # For numerical operations
import cvxpy as cp  # For convex optimization

# ---------- Case 1: n=100, m=50 ----------
n1, m1 = 100, 50  # Dimensions for Case 1
A1 = np.random.randn(m1, n1)  # Random matrix A (m1 x n1)
b1 = np.random.randn(m1, 1)  # Random vector b (m1 x 1)
Q1 = np.random.randn(m1, m1)  # Random matrix Q (m1 x m1)
Q1 = Q1 @ Q1.T + 1e-3 * np.eye(m1)  # Make Q symmetric positive definite

# ---------- Case 2: n=50, m=100 ----------
n2, m2 = 50, 100  # Dimensions for Case 2
A2 = np.random.randn(m2, n2)  # Random matrix A (m2 x n2)
b2 = np.random.randn(m2, 1)  # Random vector b (m2 x 1)
Q2 = np.random.randn(m2, m2)  # Random matrix Q (m2 x m2)
Q2 = Q2 @ Q2.T + 1e-3 * np.eye(m2)  # Make Q symmetric positive definite

# --------- Check convexity via Hessian matrix A^T Q A ---------
def is_convex(A, Q):
    H = A.T @ Q @ A  # Compute Hessian
    eigvals = np.linalg.eigvalsh(H)  # Eigenvalues
    return np.all(eigvals >= 0)  # Check all are non-negative

# --------- Closed-form analytical solution ---------
def analytical_solution(A, b, Q):
    AtQ = A.T @ Q  # Compute A^T Q
    return np.linalg.solve(AtQ @ A, AtQ @ b)  # Solve x = (A^T Q A)^-1 A^T Q b

# --------- Gradient descent algorithm ---------
def grad_descent_solver(A, b, Q, x0, lr=1e-4, max_iter=1000, tol=1e-6):
    x = x0.copy()  # Initialize x
    for _ in range(max_iter):  # Iterate
        grad = 2 * A.T @ Q @ (A @ x - b)  # Compute gradient
        x_new = x - lr * grad  # Update x
        if np.linalg.norm(x_new - x) < tol:  # Check convergence
            break
        x = x_new  # Update
    return x  # Return final x

# --------- CVX optimization ---------
def cvx_solution(A, b, Q, n):
    x = cp.Variable((n, 1))  # Define variable
    objective = cp.Minimize(cp.quad_form(A @ x - b, Q))  # Objective function
    problem = cp.Problem(objective)  # Define problem
    problem.solve()  # Solve it
    return x.value  # Return solution

# ---------- Solve for Case 1 ----------
print("==== Case 1: n=100, m=50 ====")
print("Convexity check:", is_convex(A1, Q1))  # Show convexity
x1_ana = analytical_solution(A1, b1, Q1)  # Analytical solution
print("Analytical Solution (first 5):\n", x1_ana[:5])  # Display
x1_grad = grad_descent_solver(A1, b1, Q1, np.zeros((n1, 1)))  # Gradient descent
print("Gradient Descent Solution (first 5):\n", x1_grad[:5])
x1_cvx = cvx_solution(A1, b1, Q1, n1)  # CVX solution
print("CVX Solution (first 5):\n", x1_cvx[:5])
print("||Analytical - CVX|| =", np.linalg.norm(x1_ana - x1_cvx))  # Difference

# ---------- Solve for Case 2 ----------
print("\n==== Case 2: n=50, m=100 ====")
print("Convexity check:", is_convex(A2, Q2))  # Show convexity
x2_ana = analytical_solution(A2, b2, Q2)  # Analytical solution
print("Analytical Solution (first 5):\n", x2_ana[:5])
x2_grad = grad_descent_solver(A2, b2, Q2, np.zeros((n2, 1)))  # Gradient descent
print("Gradient Descent Solution (first 5):\n", x2_grad[:5])
x2_cvx = cvx_solution(A2, b2, Q2, n2)  # CVX solution
print("CVX Solution (first 5):\n", x2_cvx[:5])
print("||Analytical - CVX|| =", np.linalg.norm(x2_ana - x2_cvx))  # Difference


==== Case 1: n=100, m=50 ====
Convexity check: False
Analytical Solution (first 5):
 [[-0.77721949]
 [ 0.51543992]
 [ 0.18418562]
 [-0.46219993]
 [ 0.49882287]]
Gradient Descent Solution (first 5):
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
CVX Solution (first 5):
 [[ 0.12957576]
 [-0.11776331]
 [ 0.00036603]
 [ 0.01926191]
 [-0.16506777]]
||Analytical - CVX|| = 8.368994364637098

==== Case 2: n=50, m=100 ====
Convexity check: True
Analytical Solution (first 5):
 [[-0.10992539]
 [ 0.22639632]
 [-0.01490781]
 [-0.01882382]
 [-0.02554648]]
Gradient Descent Solution (first 5):
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
CVX Solution (first 5):
 [[-0.10992539]
 [ 0.22639632]
 [-0.01490781]
 [-0.01882382]
 [-0.02554648]]
||Analytical - CVX|| = 8.031018926657567e-14


C:\Users\장윤수\AppData\Local\Temp\ipykernel_19728\594425895.py:33: RuntimeWarning: overflow encountered in matmul
  grad = 2 * A.T @ Q @ (A @ x - b)  # Compute gradient
C:\Users\장윤수\AppData\Local\Temp\ipykernel_19728\594425895.py:33: RuntimeWarning: invalid value encountered in matmul
  grad = 2 * A.T @ Q @ (A @ x - b)  # Compute gradient
